services:
  db_orthanc:
    container_name: db_orthanc
    image: mariadb:10.6-focal
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-pmiv-root"]
      timeout: 5s
      retries: 10
    command:
      [
        mysqld,
        --default-authentication-plugin=ed25519,
        --log-bin-trust-function-creators=1,
      ]
    volumes: ["index_orthanc:/var/lib/mariadb:Z"]
    networks:
      - orthanc-db
    environment:
      MARIADB_PASSWORD: orthanc_pass
      MARIADB_USER: orthanc
      MARIADB_DATABASE: orthanc
      MARIADB_ROOT_PASSWORD: miv-root

  db_auth:
    container_name: db_auth
    image: mariadb:10.6-focal
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-pmiv-root"]
      timeout: 5s
      retries: 10
    networks:
      - auth-db
    command:
      [
        mysqld,
        --default-authentication-plugin=ed25519,
        --log-bin-trust-function-creators=1,
      ]
    volumes:
      - "index_account_data:/var/lib/mariadb:Z"
      - "./InitDBs:/docker-entrypoint-initdb.d"
    env_file:
      - ./orthProxy/.orth_proxy.env

  orth_proxy:
    container_name: orth_proxy
    build:
      context: ./orthanc
      dockerfile: dockerfile_orthanc
    image: orthanc-with-modules
    depends_on:
      db_orthanc:
          condition: service_healthy
      db_auth:
          condition: service_healthy
    volumes:
      - ./orthProxy/python/:/etc/orthanc/python-scripts/
    ports:
      - "4243:4242"
    networks:
      - orthanc-db
      - kong-net
    env_file:
      - ./db_auth.env


  orthanc:
    container_name: orthanc
    build:
      context: ./orthanc
      dockerfile: dockerfile_orthanc
    image: orthanc-with-modules
    depends_on:
      db_orthanc:
          condition: service_healthy
      db_auth:
          condition: service_healthy
    ports: 
      - "8042:8042"
      - "4242:4242"
    networks:
      - orthanc-db
      - kong-net
      - auth-db
    volumes:
      - ./orthanc/python-scripts/:/etc/orthanc/python-scripts/
    env_file:
      - ./orthanc/.orthanc.env
      

  auth:
    container_name: auth
    build: 
      context: ..
      dockerfile: Infra/dockerfile_backend
    image: backend
    env_file:
      - .backend.env
    networks:
      - kong-net
      - auth-db
    volumes:
      - ../Backend:/app
      - ../Common:/Common
    command: nodemon /app/microservices/auth.ts
    depends_on:
      db_auth:
        condition: service_healthy
  
  account_data:
    container_name: account_data
    build: 
      context: ..
      dockerfile: Infra/dockerfile_backend
    image: account_data
    env_file:
      - .backend.env
    networks:
      - kong-net
      - auth-db
    volumes:
      - ../Backend:/app
      - ../Common:/Common
    command: nodemon /app/microservices/account_data.ts
    depends_on:
      db_auth:
        condition: service_healthy

  users:
    container_name: users
    build: 
      context: ..
      dockerfile: Infra/dockerfile_backend
    image: users
    env_file:
      - .backend.env
    networks:
      - kong-net
      - auth-db
    volumes:
      - ../Backend:/app
      - ../Common:/Common
    command: nodemon /app/microservices/users.ts
    depends_on:
      db_auth:
        condition: service_healthy

  kong-gateway:
    container_name: kong_gateway
    image: kong:3.5
    ports:
      - 8000:8000
    environment:
      - "KONG_DATABASE=off"
      - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout" 
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout" 
      - "KONG_PROXY_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001" 
    networks:
      - kong-net
    volumes:
      - ./kong_gateway/kong.yaml:/kong/declarative/kong.yml


volumes:
  storage:
  index_orthanc:
  index_account_data:
networks:
  kong-net:
    driver: bridge
  orthanc-db:
    driver: bridge
  auth-db:
    driver: bridge