_format_version: "1.1"
_transform: true

services:
  - name: account_data
    url: http://account_data:3000/
  - name: jwt
    url: http://auth:3000/
  - name: users
    url: http://users:3000/
  - name: orthanc
    url: http://orthanc:8042/
routes:
  - name: users-route
    service: users
    strip_path: true
    paths:
      - /users
  - name: ws-acc-route
    service: account_data
    strip_path: false
    paths:
      - /socket.io
  - name: acc-route
    service: account_data
    strip_path: true
    paths:
      - /acc_data
  - name: orthanc-route
    service: orthanc
    strip_path: false
    paths:
      - /studies
      - /all_studies
      - /series
      - /instances
      - /patients
  - name: peer-route
    service: orthanc
    strip_path: true
    paths:
      - /peer
  - name: jwt-route
    service: jwt
    paths:
      - /
plugins:
  - name: jwt
    route: acc-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    route: ws-acc-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    route: users-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    route: orthanc-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    route: peer-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
consumers:
  - username: backend-jwt
jwt_secrets:
  - consumer: backend-jwt

