_format_version: "1.1"
_transform: true

services:
  - name: account_data
    url: http://account_data:3000/
  - name: jwt
    url: http://auth:3000/
  - name: orthanc
    url: http://orthanc:8042/
routes:
  - name: backend-route
    service: account_data
    strip_path: true
    paths:
      - /acc_data
  - name: orthanc-route
    service: orthanc
    strip_path: false
    paths:
      - /studies
      - /series
      - /instances
      - /patients
      - /all_patients
      - /all_doctors
  - name: jwt-route
    service: jwt
    paths:
      - /
plugins:
  - name: jwt
    route: backend-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    route: orthanc-route
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
consumers:
  - username: backend-jwt
jwt_secrets:
  - consumer: backend-jwt